### PR TITLE
Improve docker image names and tags

### LINKED ISSUE #8: Default docker image version label should contain a unique build id

### PR DESCRIPTION
**Pull request by meltsufin**
Fixes #8 and #9.

Moving #10 to a local branch.

### CODE REVIEW

**Comment by meltsufin** [comment]
@aslo PTAL

**Comment by aslo** [comment]
LGTM - I think the simpler tag list is fine for the time being

**Comment by gregw** [comment]
Note that thinks like ALPN depend on a specific version of the JRE and will not work with `latest`.  If the JRE is updated then we often have to update the ALPN release to match - so there is no automatic upgrade path.  This will be better in JRE9, where ALPN will be supported natively.

But even then you want the ability to depend on a specific JRE version so you can work on JRE specific debugging.

**Comment by meltsufin** [comment]
Tagging scheme discussion should continue here: #16.

**Pull request merged**
