### PR TITLE
Local cloud build support

### PR DESCRIPTION
**Pull request by meltsufin**
@aslo At the moment the structure tests step fails, but I'm not exactly sure why. Can you take a look?

### CODE REVIEW

**Comment by aslo** [comment]
I'm seeing this behavior too. The issue comes up when trying to run the structure_test container. It needs to run docker-within-docker, and apparently there's an issue getting the workspace to mount within the inner container. I'll see if I can figure out why.

**Comment by duggelz** [comment]
Pending fix in https://github.com/GoogleCloudPlatform/runtimes-common/pull/123

**Comment by aslo** [comment]
:+1: thanks @duggelz

**Comment by meltsufin** [comment]
I think the workspace issue is now resolved. Thanks @duggelz!
However, I'm still getting an error on  cleanup of the temp directory.

```
Build completed successfully
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/target/checkstyle-result.xml’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/target/checkstyle-cachefile’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/target/checkstyle-suppressions.xml’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/target/checkstyle-checker.xml’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/target/failsafe-reports/failsafe-summary.xml’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/openjdk8/target/checkstyle-result.xml’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/openjdk8/target/checkstyle-cachefile’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/openjdk8/target/test-classes/structure.yaml’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/openjdk8/target/checkstyle-suppressions.xml’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/openjdk8/target/checkstyle-checker.xml’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/openjdk8/target/docker/setup-env.bash’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/openjdk8/target/docker/docker-entrypoint.bash’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/openjdk8/target/docker/sid.list’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/openjdk8/target/docker/Dockerfile’: Permission denied
rm: cannot remove ‘/tmp/tmp.1roGyIUoh5/openjdk8/target/failsafe-reports/failsafe-summary.xml’: Permission denied
Traceback (most recent call last):
  File "<stdin>", line 324, in <module>
  File "<stdin>", line 320, in main
  File "<stdin>", line 277, in local_cloudbuild
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/google/home/meltsufin/projects/openjdk-runtime/target/cloudbuild_local.sh']' returned non-zero exit status 1
```

It looks like the `cloudbuild_local.sh` script is executing under my normal user `meltsufin`, while those files generated during the build are owned by `root`.

**Comment by duggelz** [comment]
Hmm, those cleanup errors are annoying and I'm not sure how to fix them.

**Comment by meltsufin** [comment]
@druggelz Should we just suppress the errors then?
Also, maybe this cleanup should be moved into a `trap` instruction?
`trap 'rm -rf ...' EXIT`

**Comment by duggelz** [comment]
Good idea, I will make it a trap.  Also, I should be able to do the 'rm' inside a generic 'debian' docker container so it can delete /workspace as root.

**Comment by meltsufin** [comment]
@duggelz Seems to work, except for the comment I made on the PR regarding the script output.

**Comment by meltsufin** [comment]
@duggelz @aslo Seems to work great now! Ready for final review.

**Comment by meltsufin** [comment]
Created #70 to track that issue. We should ask the Cloud Build team - what happened?

**Pull request merged**
