### PR TITLE
Double quote array expansions

### PR DESCRIPTION
**Pull request by Androbin**

### CODE REVIEW

**Comment by meltsufin** [comment]
@Androbin Thank you for your contribution.
@ChengyuanZhao Please review.

**Comment by Androbin** [comment]
Any updates on this yet?

**Comment by meltsufin** [comment]
@Androbin If you don't mind, may I ask about your motivation for contributing to the project? We welcome all useful contributions, but I'm just curious if you are a user of the runtime or you just randomly discovered this project? Thanks!

**Comment by Androbin** [comment]
@meltsufin Some time ago I have noticed how easy it is to produce subtle bugs in Shell code.
I have learned about various errors and sometimes I go through some projects and clean up various potential bugs.

**Comment by meltsufin** [comment]
OK thanks for the clarification!

**Pull request merged**
